#!/usr/bin/env python3
"""
Script para diagnosticar el estado de las ubicaciones GBP y limpiar datos obsoletos
"""

def main():
    print("🔍 DIAGNÓSTICO: Problema de ubicaciones GBP obsoletas")
    print()
    print("📊 Los errores muestran que:")
    print("   ❌ Todas las ubicaciones GBP están dando error 404 (no existen)")
    print("   ❌ Las imágenes de Facebook dan 403 (inaccesibles)")
    print("   ❌ No quedan ubicaciones activas para publicar")
    print()
    print("🛠️ SOLUCIÓN: Necesitas actualizar las ubicaciones GBP")
    print()
    print("1️⃣ Primero, ejecuta este SQL para ver el estado actual:")
    print()
    print("-- Ver ubicaciones que están marcadas como activas")
    print("SELECT COUNT(*) as ubicaciones_activas FROM gbp_locations WHERE activa = true;")
    print()
    print("-- Ver cuántas se marcaron como inactivas hoy")
    print("SELECT COUNT(*) as marcadas_inactivas_hoy")
    print("FROM gbp_locations") 
    print("WHERE activa = false")
    print("  AND updated_at >= CURRENT_DATE;")
    print()
    print("-- Ver empresas sin ubicaciones activas")
    print("SELECT fp.empresa_id, COUNT(gl.location_name) as ubicaciones_activas")
    print("FROM facebook_paginas fp")
    print("LEFT JOIN gbp_locations gl ON fp.empresa_id = gl.empresa_id AND gl.activa = true")
    print("WHERE fp.publicar_en_gbp = true")
    print("GROUP BY fp.empresa_id")
    print("HAVING COUNT(gl.location_name) = 0;")
    print()
    print("2️⃣ Para limpiar los datos problemáticos:")
    print()
    print("-- Marcar TODAS las ubicaciones como inactivas (reset completo)")
    print("UPDATE gbp_locations SET activa = false WHERE activa = true;")
    print()
    print("-- Deshabilitar publicación GBP hasta que tengas ubicaciones válidas")
    print("UPDATE facebook_paginas SET publicar_en_gbp = false WHERE publicar_en_gbp = true;")
    print()
    print("3️⃣ Alternativa más segura - Solo procesar publicaciones sin imagen:")
    print()
    print("💡 ¿Quieres que modifique el job para que:")
    print("   ✅ Solo procese publicaciones de TEXTO (sin imágenes)")
    print("   ✅ Solo use las pocas ubicaciones GBP que aún funcionan")
    print("   ✅ Evite todos los errores de imágenes y ubicaciones inválidas")

if __name__ == "__main__":
    main()